name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate GitHub Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: akritiofficial26
          outputs: |
            dist/github-snake.svg?color_snake=#c084fc&color_dots=#f3e8ff,#e9d5ff,#c084fc,#a855f7,#7e22ce
            dist/github-snake-pink.svg?color_snake=#c084fc&color_dots=#f3e8ff,#e9d5ff,#c084fc,#a855f7,#7e22ce

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
